# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6c623c5559b4eed0a6fc62f9bbbf9b2ec0b92b596de83feb97e663e722884bb456fa3683f35a00e4fae0e010c5a5bcbcc3436406b05c3bba5b65a336642a13b
  # The following 2 keys are for using Stripe payments in a test environment.  Later, the API Keys in deployment (real payments), should be pulled from environmental variables, rather than hardcoded.
  # Should also probably remove these keys when pushing to GitHub
  stripe_publishable_key: pk_test_ASN5FTFklfzljiOSDQaFAZSy
  stripe_secret_key: sk_test_bMBZ4NuZYyuahXPNiOLSTnac

test:
  secret_key_base: 47496bef7f3a82888c3daaaf2bc699bc149bfed02308f24d867867db7a87b4f52aa63de4a679043ab96c64ff02726f61176609942f8f826e19da59c416f435dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
